### ISSUE TITLE
Good Boy License vs company usability

### ISSUE THREAD

**Issue by quecg2** [icons8/flat-color-icons#5]
Your "Good Boy License" is funny but implies you don't allow companies to use your icons without  specifying the license in their license documents and what are the constraints (they are funny but for a customer seeing those rules, it's a bad joke so no company would use your icons).

--> You should specifically in your license file that we can choose between the "Good Boy License" or a kind of public domain license.

**Comment by visualpharm** [comment]
You can. It's double licensed as standard MIT.
quecg2 <notifications@github.com> schrieb am Sa., 4. Juli 2015 um 20:06:

**Comment by quecg2** [comment]
I didn't see the last line of the license document, sorry.

**Comment by visualpharm** [comment]
Thanks for asking! Maybe we should make it more visible.
